// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASffU9qVHUVhD39lEUAG7bOIjvzfWevjQ',
    appId: '1:132616584484:web:d1cf2ced9d35ac3ef307b1',
    messagingSenderId: '132616584484',
    projectId: 'yks-deneme-takip',
    authDomain: 'yks-deneme-takip.firebaseapp.com',
    storageBucket: 'yks-deneme-takip.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJhNvlHemlbXOkHfOoJGmtfysqmNT1b0',
    appId: '1:132616584484:android:56403cd72881d153f307b1',
    messagingSenderId: '132616584484',
    projectId: 'yks-deneme-takip',
    storageBucket: 'yks-deneme-takip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMR_uM47k4RFi2durr73cBZXIsUnhdQs8',
    appId: '1:132616584484:ios:d9ea4dbdb44da712f307b1',
    messagingSenderId: '132616584484',
    projectId: 'yks-deneme-takip',
    storageBucket: 'yks-deneme-takip.firebasestorage.app',
    iosBundleId: 'com.example.yksDenemeTakip2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMR_uM47k4RFi2durr73cBZXIsUnhdQs8',
    appId: '1:132616584484:ios:d9ea4dbdb44da712f307b1',
    messagingSenderId: '132616584484',
    projectId: 'yks-deneme-takip',
    storageBucket: 'yks-deneme-takip.firebasestorage.app',
    iosBundleId: 'com.example.yksDenemeTakip2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASffU9qVHUVhD39lEUAG7bOIjvzfWevjQ',
    appId: '1:132616584484:web:868b2e4bb08745e9f307b1',
    messagingSenderId: '132616584484',
    projectId: 'yks-deneme-takip',
    authDomain: 'yks-deneme-takip.firebaseapp.com',
    storageBucket: 'yks-deneme-takip.firebasestorage.app',
  );
}
